### PR TITLE
Adding parameter 'bsg' to make code accessible to earlier genome builds

### PR DESCRIPTION
**Pull request by emm13**
Dear Javier and Rachel, 

I have been working with some mutation data that is on an hg18 build (TCGA - COAD and OVCA mutations) which did not work with the current version of the function 'mut.to.sigs.input.R'. 

My suggestion is to generalise the function so it can accept the Genome annotation package as an input parameter 'bsg'. I'm not sure if I have done it in the most elegant or sensible way possible but I am keen to hear your thoughts on it. 

I must confess this is my first interaction with Github so please forgive any novice mistakes and thank you for your time. 

Have a nice afternoon!

### CODE REVIEW

**Comment by raerose01** [comment]
Hi, 

I have used your code, altered it to match some of the package requirements, and included it as a new branch called 'allow-other-genome-builds'. It seems to work ok for me, but let me know if it works the way you were expecting, and then I can merge it back.

Thanks,

Rachel

**Comment by emm13** [comment]
Hi Rachel,

I will take a look at it and get back to you ASAP.

Have a nice day,

Manasa

**Comment by emm13** [comment]
Dear Rachel,

I have tested this on my data - works beautifully. Please feel free to
commit changes. When will the next release of the R-package be ?

Thank you!

Manasa

**Comment by raerose01** [comment]
Great, will incorporate them. And I plan on submitting a new version of the package in the next week or so.

**Pull request merged**
